version: '3.8'

services:
  mysql:
    image: mysql:8.0.28
    container_name: healthverse-mysql
    platform: linux/amd64
    volumes:
      - ./datadir/mysql:/var/lib/mysql
    ports:
      - 9999:3306
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-filesystem=utf8mb4
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --max_allowed_packet=32505856
      --lower-case-table-names=1
      --max-connections=3000
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthverse
      MYSQL_USER: healthverse
      MYSQL_PASSWORD: healthverse
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
